{{- if .Values.postgres.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "presto.postgres.fullname" . }}-app-state-config
  labels:
    component: postgres
{{ include "presto.labels" . | indent 4 }}
data:
  app-state-config.sql: |-
    {{- range .Values.view_state_apps }}
    CREATE USER {{ .db.user | required "view_state_apps app db.user must be set" }} WITH PASSWORD '{{ .db.password | required "view_state_apps app db.password must be set" }}';
    CREATE DATABASE {{ .db.name }} WITH OWNER {{ .db.user }};
    {{- end }}
{{- end }}