{{- if .Values.postgres.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "presto.postgres.fullname" . }}-app-state-config
  labels:
    component: postgres
{{ include "presto.labels" . | indent 4 }}
data:
  app-state-config.sql: |-
    {{- range $key, $value := .Values.view_state_apps }}
    CREATE USER {{ $value.db.user | required "view_state_apps app db.user must be set" }} WITH PASSWORD '{{ $value.db.password | required "view_state_apps app db.password must be set" }}';
    CREATE DATABASE {{ $value.db.name }} WITH OWNER {{ $value.db.user }};
    {{- end }}
{{- end }}