---
version: '3.4'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
    - "KAFKA_ADVERTISED_LISTENERS=INSIDE://:9094,OUTSIDE://${HOST_IP:-localhost}:9092"
    - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
    - "KAFKA_LISTENERS=INSIDE://:9094,OUTSIDE://:9092"
    - "KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE"
    - "KAFKA_CREATE_TOPICS=topic:1:1,event-stream:1:1"
    - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
    healthcheck:
      test: ["CMD-SHELL", "cat /opt/kafka/logs/server.log | grep \"Previous leader epoch was -1\""]
      interval: 10s
      timeout: 20s
      retries: 3
  postgres:
    logging:
      driver: none
    image: smartcitiesdata/postgres-testo:development
    ports:
    - "5432:5432"
  metastore:
    image: smartcitiesdata/metastore-testo:development
    depends_on:
    - postgres
    ports:
    - "9083:9083"
    command: >
      /bin/bash -c "
        /opt/hive-metastore/bin/schematool -dbType postgres -validate || /opt/hive-metastore/bin/schematool -dbType postgres -initSchema;
        /opt/hive-metastore/bin/start-metastore"
  minio:
    image: smartcitiesdata/minio-testo:development
    ports:
    - "9000:9000"
  presto:
    depends_on:
    - metastore
    - minio
    image: smartcitiesdata/presto-testo:development
    ports:
    - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080/v1/info | grep -q '\"starting\":false'"]
      interval: 10s
      timeout: 30s
      retries: 10