apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: acme-cert4
  namespace: cert-manager
spec:
  dnsNames:
    - prod.agnosticdataengine.com
  secretName: acme-cert-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
