apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hindsight.fullname" . }}-persist
  labels:
    {{- include "hindsight.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.persist.replicaCount }}
  selector:
    matchLabels:
      app: hindsight-persist
      {{- include "hindsight.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: hindsight-persist
        {{- include "hindsight.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "hindsight.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-persist
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "hindsight.image" . }}
          command:
            - persist/bin/persist
            - start
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BUCKET_NAME
              value: {{ .Values.global.objectStore.bucketName }}
            - name: BUCKET_REGION
              value: {{ .Values.global.objectStore.region }}
            - name: PRESTO_URL
              value: http://{{ template "presto.fullname" . }}:{{ .Values.presto.service.port }}
            - name: KAFKA_ENDPOINTS
              value: {{ template "hindsight.fullname" . }}-kafka-bootstrap:9092
            - name: REDIS_HOST
              value: {{ template "redis.host" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
