apiVersion: v1
kind: Service
metadata:
  name: {{ include "hindsight.fullname" . }}-acquire
  labels:
    app: hindsight-acquire
    {{- include "hindsight.labels" . | nindent 4 }}
spec:
  type: {{ .Values.acquire.service.type }}
  ports:
    - port: {{ .Values.acquire.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9568
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: hindsight-acquire
    {{- include "hindsight.selectorLabels" . | nindent 4 }}
