apiVersion: v1
kind: Service
metadata:
  name: {{ include "hindsight.fullname" . }}-receive
  labels:
    app: hindsight-receive
    {{- include "hindsight.labels" . | nindent 4 }}
spec:
  type: {{ .Values.receive.service.type }}
  ports:
    - port: {{ .Values.receive.service.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
    - port: 9568
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: hindsight-receive
    {{- include "hindsight.selectorLabels" . | nindent 4 }}
