apiVersion: v1
kind: Service
metadata:
  name: {{ include "hindsight.fullname" . }}-receive-tcp
  labels:
    app: hindsight-receive
    {{- include "hindsight.labels" . | nindent 4 }}
spec:
  type: {{ .Values.receive.service_tcp.type }}
  ports:
    - port: {{ .Values.receive.service_tcp.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    app: hindsight-receive
    {{- include "hindsight.selectorLabels" . | nindent 4 }}
