---
version: '3.4'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
    - "KAFKA_ADVERTISED_LISTENERS=INSIDE://:9094,OUTSIDE://${HOST_IP:-localhost}:9092"
    - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
    - "KAFKA_LISTENERS=INSIDE://:9094,OUTSIDE://:9092"
    - "KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE"
    - "KAFKA_CREATE_TOPICS=topic:1:1,event-stream:1:1"
    - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
    healthcheck:
      test: ["CMD-SHELL", "cat /opt/kafka/logs/server.log | grep \"Previous leader epoch was -1\""]
      interval: 10s
      timeout: 20s
      retries: 3
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 20s
      retries: 3
