Mox.defmock(Writer.PrestoMock, for: Writer)
Mox.defmock(Persist.WriterMock, for: Writer)
Mox.defmock(Persist.DLQMock, for: Writer)
Mox.defmock(BroadwayMock, for: [Test.StartLink, Broadway])
Mox.defmock(Persist.LoaderMock, for: [Test.StartLink, GenServer])
Mox.defmock(Persist.DataFileMock, for: Persist.DataFile)
Mox.defmock(Persist.UploaderMock, for: Persist.Uploader)
Mox.defmock(Persist.TableCreatorMock, for: Persist.TableCreator)
Mox.defmock(Persist.CompactorMock, for: Persist.Compactor)
