Mox.defmock(Writer.PrestoMock, for: Writer)
Mox.defmock(Persist.WriterMock, for: Writer)
Mox.defmock(Persist.DLQMock, for: Writer)
Mox.defmock(BroadwayMock, for: [Test.StartLink, Broadway])
Mox.defmock(Persist.LoaderMock, for: [Test.StartLink, GenServer])
