---
version: "3.4"
services:
  postgres:
    logging:
      driver: none
    image: smartcitiesdata/postgres-testo:development
    ports:
    - "5432:5432"
  metastore:
    image: smartcitiesdata/metastore-testo:development
    depends_on:
    - postgres
    ports:
    - "9083:9083"
    command: >
      /bin/bash -c "
        /opt/hive-metastore/bin/schematool -dbType postgres -validate || /opt/hive-metastore/bin/schematool -dbType postgres -initSchema;
        /opt/hive-metastore/bin/start-metastore"
  minio:
    image: smartcitiesdata/minio-testo:development
    ports:
    - "9000:9000"
  presto:
    depends_on:
    - metastore
    - minio
    image: smartcitiesdata/presto-testo:development
    ports:
    - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080/v1/info | grep -q '\"starting\":false'"]
      interval: 10s
      timeout: 30s
      retries: 10
