{{- if .Values.global.objectStore.minio.enabled -}}
{{- if .Values.minio.ingress.enable -}}
{{- $serviceName := include "presto.minio.fullname" . }}
{{- $servicePort := .Values.minio.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if or .Values.minio.ingress.annotations .Values.global.ingress.annotations }}
  annotations:
{{- if .Values.minio.ingress.annotations }}
{{ toYaml .Values.minio.ingress.annotations | trim | indent 4 }}
{{- end }}
{{- if .Values.global.ingress.annotations }}
{{ toYaml .Values.global.ingress.annotations | trim | indent 4 }}
{{- end }}
{{- end }}
  name: {{ template "presto.minio.fullname" . }}
  labels:
    component: minio
{{ include "presto.labels" . | indent 4 }}
spec:
  backend:
    serviceName: {{ $serviceName }}
    servicePort: {{ $servicePort }}
  rules:
{{- range .Values.minio.ingress.hosts }}
{{- $url := splitList "/" . }}
  - host: {{ first $url }}
    http:
      paths:
      - path: /{{ rest $url | join "/" }}
        backend:
          serviceName: {{ default $serviceName $.Values.minio.ingress.serviceName }}
          servicePort: {{ default $servicePort $.Values.minio.ingress.servicePort }}
{{- end }}
{{- end }}
{{- end }}
