apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hindsight.fullname" . }}-broadcast
  labels:
    app: hindsight-broadcast
    {{- include "hindsight.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: hindsight-broadcast
      {{- include "hindsight.labels" . | nindent 6 }}
  endpoints:
  - port: metrics
