apiVersion: v1
kind: Service
metadata:
  name: {{ include "hindsight.fullname" . }}-orchestrate
  labels:
    app: hindsight-orchestrate
    {{- include "hindsight.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9568
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: hindsight-orchestrate
    {{- include "hindsight.selectorLabels" . | nindent 4 }}
