name: Master
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Push latest Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: inhindsight/hindsight
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  dialyzer:
    name: Cache PLT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 22.2
          elixir-version: 1.9.4
      - name: Get dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Retrieve PLT
        uses: actions/cache@v1
        with:
          path: .dialyzer
          key: plt-master
      - name: Run dialyzer
        run: |
          mix dialyzer
