name: Release
on:
  release:
    types:
      - created
jobs:
  publish:
    name: Push release Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: inhindsight/hindsight
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
